// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4b49WdEKpmL-cL1TNQ5P6OriWqIyGgl0',
    appId: '1:665057026086:web:aa127a9561c26f8cafc6e7',
    messagingSenderId: '665057026086',
    projectId: 'payservices-7827a',
    authDomain: 'payservices-7827a.firebaseapp.com',
    storageBucket: 'payservices-7827a.firebasestorage.app',
    measurementId: 'G-JJ8DF7SXG5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqGoqjBWGSDwbvfGtr9jV2ELGJgZ9l9mU',
    appId: '1:665057026086:android:e12e3566e1ebf309afc6e7',
    messagingSenderId: '665057026086',
    projectId: 'payservices-7827a',
    storageBucket: 'payservices-7827a.firebasestorage.app',
    androidClientId:
        '665057026086-bcv6ri93i77ltu230eh3s29e08plag5o.apps.googleusercontent.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaUbJIaAyCS5JvaQxLU1-YD3dnRz5dOqM',
    appId: '1:665057026086:ios:c720119e0a5fb630afc6e7',
    messagingSenderId: '665057026086',
    projectId: 'payservices-7827a',
    storageBucket: 'payservices-7827a.firebasestorage.app',
    iosBundleId: 'app.sevenpayservice.gobuddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaUbJIaAyCS5JvaQxLU1-YD3dnRz5dOqM',
    appId: '1:665057026086:ios:c720119e0a5fb630afc6e7',
    messagingSenderId: '665057026086',
    projectId: 'payservices-7827a',
    storageBucket: 'payservices-7827a.firebasestorage.app',
    iosBundleId: 'app.sevenpayservice.gobuddy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4b49WdEKpmL-cL1TNQ5P6OriWqIyGgl0',
    appId: '1:665057026086:web:117c85861905e5cbafc6e7',
    messagingSenderId: '665057026086',
    projectId: 'payservices-7827a',
    authDomain: 'payservices-7827a.firebaseapp.com',
    storageBucket: 'payservices-7827a.firebasestorage.app',
    measurementId: 'G-JNNYKLM65G',
  );
}
